---
- hosts: all
  sudo: yes
  tasks:
   - name: pull from git
     git:
      repo: git@github.com:subrata94/demo.git
      dest: /home/ubuntu/
      update: yes
      version: master
      accept_hostkey: yes
     sudo_user: ubuntu